set(
	GUI_RESOURCES_SRCS
	"${project_dir}/gui-resources/monochrome/fonts/font_h8_Data.c"
	"${project_dir}/gui-resources/monochrome/fonts/font_h8.c"
	"${project_dir}/gui-resources/monochrome/fonts/font_h10_Data.c"
	"${project_dir}/gui-resources/monochrome/fonts/font_h10.c"
	"${project_dir}/gui-resources/monochrome/fonts/font_h12_Data.c"
	"${project_dir}/gui-resources/monochrome/fonts/font_h12.c"
	"${project_dir}/gui-resources/monochrome/fonts/font_h14_Data.c"
	"${project_dir}/gui-resources/monochrome/fonts/font_h14.c"
	"${project_dir}/gui-resources/monochrome/fonts/font_h16_Data.c"
	"${project_dir}/gui-resources/monochrome/fonts/font_h16.c"
	"${project_dir}/gui-resources/monochrome/fonts/font_h24_Data.c"
	"${project_dir}/gui-resources/monochrome/fonts/font_h24.c"
	"${project_dir}/gui-resources/monochrome/fonts/font_h32_Data.c"
	"${project_dir}/gui-resources/monochrome/fonts/font_h32.c"
)

set(
	GUI_RESOURCES_INCS
	"${project_dir}/gui-resources/monochrome/fonts"
)