set(
	GUI_RESOURCES_SRCS
	"${project_dir}/gui-resources/monochrome/font_bw_size8_Data.c"
	"${project_dir}/gui-resources/monochrome/font_bw_size8.c"
	"${project_dir}/gui-resources/monochrome/font_bw_size10_Data.c"
	"${project_dir}/gui-resources/monochrome/font_bw_size10.c"
	"${project_dir}/gui-resources/monochrome/font_bw_size12_Data.c"
	"${project_dir}/gui-resources/monochrome/font_bw_size12.c"
	"${project_dir}/gui-resources/monochrome/font_bw_size14_Data.c"
	"${project_dir}/gui-resources/monochrome/font_bw_size14.c"
	"${project_dir}/gui-resources/monochrome/font_bw_size14_bold_Data.c"
	"${project_dir}/gui-resources/monochrome/font_bw_size14_bold.c"
	"${project_dir}/gui-resources/monochrome/font_bw_size16_Data.c"
	"${project_dir}/gui-resources/monochrome/font_bw_size16.c"
	"${project_dir}/gui-resources/monochrome/font_bw_size16_bold_Data.c"
	"${project_dir}/gui-resources/monochrome/font_bw_size16_bold.c"
	"${project_dir}/gui-resources/monochrome/font_bw_size24_Data.c"
	"${project_dir}/gui-resources/monochrome/font_bw_size24.c"
)

set(
	GUI_RESOURCES_INCS
	"${project_dir}/gui-resources/monochrome"
)