set(GUI_ORANGE_GRAY_PICTURES_SRCS
	"${project_dir}/gui-orange-gray/pictures-src/button64x24_button64x24disabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/button64x24_button64x24enabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/button64x24_button64x24focused.c"
	"${project_dir}/gui-orange-gray/pictures-src/button64x24_button64x24pressed.c"
	"${project_dir}/gui-orange-gray/pictures-src/button64x24_button64x24selected.c"

	"${project_dir}/gui-orange-gray/pictures-src/button100x22_button100x22disabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/button100x22_button100x22enabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/button100x22_button100x22focused.c"
	"${project_dir}/gui-orange-gray/pictures-src/button100x22_button100x22pressed.c"
	"${project_dir}/gui-orange-gray/pictures-src/button100x22_button100x22selected.c"

	"${project_dir}/gui-orange-gray/pictures-src/button193x44_button193x44disabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/button193x44_button193x44enabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/button193x44_button193x44focused.c"
	"${project_dir}/gui-orange-gray/pictures-src/button193x44_button193x44pressed.c"
	"${project_dir}/gui-orange-gray/pictures-src/button193x44_button193x44selected.c"

	"${project_dir}/gui-orange-gray/pictures-src/checkbox18x18_checkbox18x18checked_dis.c"
	"${project_dir}/gui-orange-gray/pictures-src/checkbox18x18_checkbox18x18checked_ena.c"
	"${project_dir}/gui-orange-gray/pictures-src/checkbox18x18_checkbox18x18checked_foc.c"
	"${project_dir}/gui-orange-gray/pictures-src/checkbox18x18_checkbox18x18checked_press.c"
	"${project_dir}/gui-orange-gray/pictures-src/checkbox18x18_checkbox18x18unchecked_dis.c"
	"${project_dir}/gui-orange-gray/pictures-src/checkbox18x18_checkbox18x18unchecked_ena.c"
	"${project_dir}/gui-orange-gray/pictures-src/checkbox18x18_checkbox18x18unchecked_foc.c"
	"${project_dir}/gui-orange-gray/pictures-src/checkbox18x18_checkbox18x18unchecked_press.c"

	"${project_dir}/gui-orange-gray/pictures-src/checkbox36x18_checkbox36x18checked_dis.c"
	"${project_dir}/gui-orange-gray/pictures-src/checkbox36x18_checkbox36x18checked_ena.c"
	"${project_dir}/gui-orange-gray/pictures-src/checkbox36x18_checkbox36x18checked_foc.c"
	"${project_dir}/gui-orange-gray/pictures-src/checkbox36x18_checkbox36x18checked_press.c"
	"${project_dir}/gui-orange-gray/pictures-src/checkbox36x18_checkbox36x18unchecked_dis.c"
	"${project_dir}/gui-orange-gray/pictures-src/checkbox36x18_checkbox36x18unchecked_ena.c"
	"${project_dir}/gui-orange-gray/pictures-src/checkbox36x18_checkbox36x18unchecked_foc.c"
	"${project_dir}/gui-orange-gray/pictures-src/checkbox36x18_checkbox36x18unchecked_press.c"

	"${project_dir}/gui-orange-gray/pictures-src/filter_slider_background150x18.c"
	"${project_dir}/gui-orange-gray/pictures-src/filter_slider_left150x18dis.c"
	"${project_dir}/gui-orange-gray/pictures-src/filter_slider_left150x18ena.c"
	"${project_dir}/gui-orange-gray/pictures-src/filter_slider_left150x18foc.c"
	"${project_dir}/gui-orange-gray/pictures-src/filter_slider_left150x18press.c"
	"${project_dir}/gui-orange-gray/pictures-src/filter_slider_left150x18sel.c"
	"${project_dir}/gui-orange-gray/pictures-src/filter_slider_right150x18dis.c"
	"${project_dir}/gui-orange-gray/pictures-src/filter_slider_right150x18ena.c"
	"${project_dir}/gui-orange-gray/pictures-src/filter_slider_right150x18foc.c"
	"${project_dir}/gui-orange-gray/pictures-src/filter_slider_right150x18press.c"
	"${project_dir}/gui-orange-gray/pictures-src/filter_slider_right150x18sel.c"

	"${project_dir}/gui-orange-gray/pictures-src/grid320x100_grid320x100.c"

	"${project_dir}/gui-orange-gray/pictures-src/hslider_hpointer12x12disabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/hslider_hpointer12x12enabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/hslider_hpointer12x12focused.c"
	"${project_dir}/gui-orange-gray/pictures-src/hslider_hpointer12x12pressed.c"
	"${project_dir}/gui-orange-gray/pictures-src/hslider_hpointer12x12selected.c"
	"${project_dir}/gui-orange-gray/pictures-src/hslider_lefttrack12x280disabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/hslider_lefttrack12x280enabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/hslider_righttrack12x280disabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/hslider_righttrack12x280enabled.c"

	"${project_dir}/gui-orange-gray/pictures-src/tab2_tab160x24disabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/tab2_tab160x24enabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/tab2_tab160x24focused.c"
	"${project_dir}/gui-orange-gray/pictures-src/tab2_tab160x24pressed.c"
	"${project_dir}/gui-orange-gray/pictures-src/tab2_tab160x24selected.c"

	"${project_dir}/gui-orange-gray/pictures-src/tab5_tab64x24disabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/tab5_tab64x24enabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/tab5_tab64x24focused.c"
	"${project_dir}/gui-orange-gray/pictures-src/tab5_tab64x24pressed.c"
	"${project_dir}/gui-orange-gray/pictures-src/tab5_tab64x24selected.c"

	"${project_dir}/gui-orange-gray/pictures-src/vslider_bottomtrack12x200disabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/vslider_bottomtrack12x200enabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/vslider_toptrack12x200disabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/vslider_toptrack12x200enabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/vslider_vpointer12x12disabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/vslider_vpointer12x12enabled.c"
	"${project_dir}/gui-orange-gray/pictures-src/vslider_vpointer12x12focused.c"
	"${project_dir}/gui-orange-gray/pictures-src/vslider_vpointer12x12pressed.c"
	"${project_dir}/gui-orange-gray/pictures-src/vslider_vpointer12x12selected.c"

	"${project_dir}/gui-orange-gray/pictures-src/windows_window240x176.c"
	"${project_dir}/gui-orange-gray/pictures-src/windows_window240x110.c"
)

set(GUI_ORANGE_GRAY_PICTURES_INCS
	"${project_dir}/gui-orange-gray/pictures-src"
)