set(GUI_ORANGE_GRAY_CONTROLS_SRCS
	"${lib_source_files_dir}/gui-orange-gray/controls-src/OGButton64x24.cpp"
	"${lib_source_files_dir}/gui-orange-gray/controls-src/OGButton100x22.cpp"
	"${lib_source_files_dir}/gui-orange-gray/controls-src/OGCheckBoxH18.cpp"
	"${lib_source_files_dir}/gui-orange-gray/controls-src/OGCommon.cpp"
	"${lib_source_files_dir}/gui-orange-gray/controls-src/OGDialogCloseBase.cpp"
	"${lib_source_files_dir}/gui-orange-gray/controls-src/OGDialogCloseBase240x110.cpp"
	"${lib_source_files_dir}/gui-orange-gray/controls-src/OGHorizontalSliderLabel.cpp"
	"${lib_source_files_dir}/gui-orange-gray/controls-src/OGNumericUpDown.cpp"
	"${lib_source_files_dir}/gui-orange-gray/controls-src/OGRadioButton64x24.cpp"
	"${lib_source_files_dir}/gui-orange-gray/controls-src/OGRadioButtonH18.cpp"
	"${lib_source_files_dir}/gui-orange-gray/controls-src/OGSliderHorizontal.cpp"
	"${lib_source_files_dir}/gui-orange-gray/controls-src/OGSliderVertical.cpp"
	"${lib_source_files_dir}/gui-orange-gray/controls-src/OGTab64x24.cpp"
	"${lib_source_files_dir}/gui-orange-gray/controls-src/OGTab160x24.cpp"
	"${lib_source_files_dir}/gui-orange-gray/controls-src/OGTabControl2T.cpp"
	"${lib_source_files_dir}/gui-orange-gray/controls-src/OGTabControl5T.cpp"
	"${lib_source_files_dir}/gui-orange-gray/controls-src/OGVerticalSliderLabel.cpp"
)

set(GUI_ORANGE_GRAY_CONTROLS_INCS
	"${lib_source_files_dir}/gui-orange-gray/controls-src"
)